config/routes.rb
LesliePortfolio::Application.routes.draw do
	
	get "welcome/index"
	get "welcome/resume"
	get "welcome/samples"
	get "welcome/portfolio"
	

  root :to => "welcome#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
  
  def resume
  	send_file "#{RAILS_ROOT}/public/resources/leslie_johnson_resume.pdf", :disposition => 'inline',:type => 'application/pdf'
  end
  
  def samples
  	send_file "#{RAILS_ROOT}/public/resources/leslie_johnson_samples.pdf", :disposition => 'inline',:type => 'application/pdf'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def page_title
	  "#{controller.controller_name.titleize} | #{controller.action_name.titleize}"
	end
	
end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LesliePortfolio</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.haml
!!! 5
%html
	%head
		= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"
		= javascript_include_tag 'rails'
		
		%meta{:name => 'csrf-token', :content => form_authenticity_token}
		%meta{:name => 'csrf-param', :content => 'authenticity_token'}
		
		%title
			=page_title
			
		= stylesheet_link_tag :all
		
		/[if lt IE 9]
			= javascript_include_tag 'html5'
	%body
		#page
			= yield

app/views/welcome/index.html.haml
#content
	%p	
		= image_tag("leslie_johnson.jpg")
	%p
		= link_to '', welcome_resume_path, :id => 'button_nav_resume', :class => 'center'
	%p
		= link_to '', welcome_samples_path, :id => 'button_nav_samples', :class => 'center'
	%p
		= image_tag("portfolio.jpg")
		/= link_to 'Portfolio', welcome_portfolio_path, :id => 'button_nav_portfolio', :class => 'center'